# Generated by Django 3.0.3 on 2020-03-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200313_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_address',
            field=models.EmailField(default='None', max_length=254, unique=True),
        ),
    ]
