# Generated by Django 3.0.3 on 2020-03-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_address',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
