# Generated by Django 3.0.3 on 2020-03-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='type',
            field=models.CharField(choices=[('C', 'creditor'), ('D', 'debtor')], max_length=1),
        ),
    ]
