# Generated by Django 3.0.3 on 2020-03-06 15:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0003_simple'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Shylockentry',
        ),
        migrations.DeleteModel(
            name='Simple',
        ),
    ]
