# Generated by Django 3.0.3 on 2020-03-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20200307_0112'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shylockentry',
            table='shylockentries',
        ),
    ]
