# Generated by Django 3.0.3 on 2020-03-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20200307_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shylockentry',
            options={'verbose_name_plural': 'shylockentries'},
        ),
    ]
