# Generated by Django 3.0.3 on 2020-03-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_auto_20200308_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shylockentry',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shylockentry',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
